# ************************************************************
# Sequel Pro SQL dump
# Version 4541
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: localhost (MySQL 5.7.39)
# Database: laravel
# Generation Time: 2024-06-06 11:59:06 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table tbl_fonts
# ------------------------------------------------------------

DROP TABLE IF EXISTS `tbl_fonts`;

CREATE TABLE `tbl_fonts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `letter` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `font` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ascii` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `height` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `width` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `extra` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

LOCK TABLES `tbl_fonts` WRITE;
/*!40000 ALTER TABLE `tbl_fonts` DISABLE KEYS */;

INSERT INTO `tbl_fonts` (`id`, `letter`, `font`, `ascii`, `height`, `width`, `extra`, `created_at`, `updated_at`)
VALUES
	(1,'A','false,false,true,true,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,true,true,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true','65','10','6',NULL,'2024-04-03 15:56:15','2024-04-04 01:16:00'),
	(2,'B','true,true,true,true,true,false,true,false,false,false,true,true,true,false,false,false,false,true,true,false,false,false,true,true,true,true,true,true,true,false,true,false,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,true,true,true,true,true,true,false','66','10','6',NULL,'2024-04-03 15:57:11','2024-04-03 15:57:11'),
	(3,'C','false,false,true,true,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,true,true,false,true,true,true,true,false,false,false,true,true,false,false','67','10','6',NULL,'2024-04-03 15:57:51','2024-04-03 15:57:55'),
	(4,'D','true,true,true,true,false,false,true,false,false,true,true,false,true,false,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false,false','68','10','6',NULL,'2024-04-03 16:00:17','2024-04-03 16:00:17'),
	(5,'E','true,true,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,true,true,true','69','10','6',NULL,'2024-04-03 16:00:43','2024-04-03 16:00:43'),
	(6,'F','true,true,true,true,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false','70','10','6',NULL,'2024-04-03 16:01:43','2024-04-03 16:01:43'),
	(7,'G','false,false,true,true,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,true,true,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false,false,false,true,true,false,false','71','10','6',NULL,'2024-04-03 16:02:22','2024-04-03 16:02:22'),
	(8,'H','true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true','72','10','6',NULL,'2024-04-03 16:02:40','2024-04-03 16:02:40'),
	(9,'I','false,true,true,true,true,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,true,true,true,false','73','10','6',NULL,'2024-04-03 16:02:55','2024-04-03 16:02:55'),
	(10,'J','false,true,true,true,true,true,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,true,false,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false','74','10','6',NULL,'2024-04-03 16:06:08','2024-04-12 22:39:58'),
	(11,'K','true,false,false,false,false,true,true,false,false,false,true,true,true,false,false,true,true,false,true,false,true,true,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,false,true,true,false,false,true,false,false,true,true,false,true,false,false,false,true,true,true,false,false,false,false,true','75','10','6',NULL,'2024-04-03 16:06:32','2024-04-03 16:06:32'),
	(12,'L','true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,true,true,true','76','10','6',NULL,'2024-04-03 16:06:39','2024-04-03 16:06:39'),
	(13,'M','true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,true,true,true,true,false,true,true,false,true,true,false,true,true,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true','77','10','6',NULL,'2024-04-03 16:06:57','2024-04-03 16:06:57'),
	(14,'N','true,false,false,false,false,true,true,true,false,false,false,true,true,true,true,false,false,true,true,true,true,true,false,true,true,false,true,true,false,true,true,false,false,true,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true','78','10','6',NULL,'2024-04-03 16:07:11','2024-04-03 16:07:11'),
	(15,'O','false,false,true,true,false,false,false,true,true,true,true,false,false,true,false,false,true,false,true,true,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,false,false,true,false,false,true,true,true,true,false,false,false,true,true,false,false','79','10','6',NULL,'2024-04-03 16:08:04','2024-04-12 22:38:38'),
	(16,'P','true,true,true,true,true,false,true,false,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,true,true,true,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false','80','10','6',NULL,'2024-04-03 16:08:29','2024-04-03 16:08:29'),
	(17,'Q','false,false,true,true,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,false,false,true,false,false,true,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true','81','10','6',NULL,'2024-04-03 16:09:49','2024-04-03 16:09:49'),
	(18,'R','true,true,true,true,true,false,true,false,false,false,true,true,true,false,false,false,false,true,true,false,false,false,true,true,true,true,true,true,true,false,true,true,true,false,false,false,true,false,true,true,false,false,true,false,false,true,true,false,true,false,false,false,true,true,true,false,false,false,false,true','82','10','6',NULL,'2024-04-03 16:10:47','2024-04-03 16:10:47'),
	(19,'S','false,true,true,true,true,false,true,false,false,false,true,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,false,false,true,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,false,true,false,true,true,true,true,false','83','10','6',NULL,'2024-04-03 16:13:22','2024-04-03 16:15:58'),
	(20,'T','true,true,true,true,true,true,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false','84','10','6',NULL,'2024-04-03 16:15:27','2024-04-03 16:15:27'),
	(21,'U','true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,true,true,true,true,true,true,false,true,true,true,true,false','85','10','6',NULL,'2024-04-03 16:16:32','2024-04-03 16:16:32'),
	(22,'V','true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,true,true,false,false','86','10','6',NULL,'2024-04-03 16:16:46','2024-04-03 16:16:46'),
	(23,'W','true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,true,true,false,true,true,false,true,true,false,true,true,true,true,true,true,true,true,true,false,false,true,true,false,true,false,false,true,false','87','10','6',NULL,'2024-04-03 16:17:26','2024-04-03 16:17:26'),
	(24,'X','true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,false,false,true,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,false,false,true,false,true,true,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true','88','10','6',NULL,'2024-04-03 16:18:04','2024-04-03 16:18:04'),
	(25,'y','false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,false,false,true,false,true,true,true,true,false','121','10','6',NULL,'2024-04-03 16:18:16','2024-04-12 23:08:02'),
	(26,'Z','true,true,true,true,true,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,true,true,true,true,true','90','10','6',NULL,'2024-04-03 16:21:47','2024-04-03 16:21:47'),
	(27,'1','false,false,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,true,true,true,false','49','10','6',NULL,'2024-04-03 16:25:57','2024-04-12 22:41:11'),
	(28,'2','false,true,true,true,true,false,true,true,false,false,true,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,true,true,true,true,true','50','10','6',NULL,'2024-04-03 16:26:22','2024-04-03 16:26:22'),
	(29,'3','false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,true,true,true,false,false,false,true,true,true,false,false,false,false,false,true,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false','51','10','6',NULL,'2024-04-03 16:28:18','2024-04-03 16:31:32'),
	(30,'4','false,false,false,false,true,false,false,false,false,true,true,false,false,false,true,true,true,false,false,true,true,false,true,false,true,true,false,false,true,false,true,false,false,false,true,false,true,true,true,true,true,true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false','52','10','6',NULL,'2024-04-03 16:32:50','2024-04-03 16:32:50'),
	(31,'5','true,true,true,true,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false','53','10','6',NULL,'2024-04-03 16:33:14','2024-04-12 22:42:33'),
	(32,'6','false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,true,true,true,false,false,true,true,false,false,true,false,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false,false,false,true,true,false,false','54','10','6',NULL,'2024-04-03 16:34:19','2024-04-03 16:34:19'),
	(33,'7','true,true,true,true,true,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false','55','10','6',NULL,'2024-04-03 16:35:02','2024-04-12 22:43:03'),
	(34,'8','false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false','56','10','6',NULL,'2024-04-03 16:35:39','2024-04-03 16:36:32'),
	(35,'9','false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false','57','10','6',NULL,'2024-04-03 16:38:13','2024-04-12 22:44:01'),
	(36,'/','false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false','47','10','6',NULL,'2024-04-03 22:02:50','2024-04-03 22:04:39'),
	(37,'%','true,true,false,false,false,true,false,true,false,false,true,true,true,true,false,true,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,false,true,true,true,true,false,false,true,false,true,false,false,false,true,true','37','10','6',NULL,'2024-04-03 22:03:14','2024-04-03 22:03:14'),
	(38,'\\','true,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,true,true','92','10','6',NULL,'2024-04-03 22:04:22','2024-04-12 22:46:54'),
	(39,'[','false,true,true,true,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,false,false','91','10','6',NULL,'2024-04-03 22:05:12','2024-04-03 22:05:12'),
	(40,']','false,false,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,true,true,false','93','10','6',NULL,'2024-04-03 22:05:26','2024-04-03 22:05:26'),
	(41,'}','true,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,false,true,true,true,false,false,false,true,true,true,false,false,true,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,true,true,true,false,false,false','125','10','6',NULL,'2024-04-03 22:13:21','2024-04-03 22:13:21'),
	(42,')','true,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,true,true,true,false,false,false','41','10','6',NULL,'2024-04-03 22:13:52','2024-04-03 22:15:37'),
	(43,'(','false,false,false,true,true,true,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,true','40','10','6',NULL,'2024-04-03 22:14:41','2024-04-03 22:14:41'),
	(44,'>','true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,false','62','10','6',NULL,'2024-04-03 22:15:06','2024-04-03 22:15:06'),
	(45,'<','false,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,true','60','10','6',NULL,'2024-04-03 22:16:28','2024-04-03 22:16:55'),
	(46,'.','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false','46','10','6',NULL,'2024-04-03 22:17:04','2024-04-03 22:17:04'),
	(47,',','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,true,false,false,false','44','10','6',NULL,'2024-04-03 22:17:26','2024-04-12 22:51:35'),
	(48,'_','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,false,false,false,false,false,false','95','10','6',NULL,'2024-04-03 22:18:16','2024-04-03 22:18:16'),
	(49,'-','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','45','10','6',NULL,'2024-04-03 22:18:24','2024-04-03 22:18:24'),
	(50,'+','false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,true,true,true,true,true,true,true,true,true,true,true,true,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false','43','10','6',NULL,'2024-04-03 22:18:49','2024-04-03 22:18:49'),
	(51,'=','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','61','10','6',NULL,'2024-04-03 22:19:00','2024-04-03 22:19:00'),
	(52,'~','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,true,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','126','10','6',NULL,'2024-04-03 22:20:57','2024-04-03 22:23:34'),
	(53,'!','false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false','33','10','6',NULL,'2024-04-03 22:23:46','2024-04-03 22:23:46'),
	(54,'?','false,true,true,true,false,false,true,true,false,true,true,false,true,false,false,false,true,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false','63','10','6',NULL,'2024-04-03 22:24:54','2024-04-03 22:24:54'),
	(55,'@','false,false,false,false,false,false,false,true,true,true,true,true,true,true,false,false,false,true,true,false,false,true,false,true,true,false,true,true,false,true,true,false,true,true,false,true,true,false,false,true,true,true,true,true,false,false,false,false,false,true,true,true,true,true,false,false,false,false,false,false','64','10','6',NULL,'2024-04-03 22:28:13','2024-04-03 22:28:52'),
	(56,'#','false,false,false,false,false,false,false,true,false,false,true,false,false,true,false,false,true,false,true,true,true,true,true,true,false,true,false,false,true,false,false,true,false,false,true,false,true,true,true,true,true,true,false,true,false,false,true,false,false,true,false,false,true,false,false,false,false,false,false,false','35','10','6',NULL,'2024-04-03 22:29:41','2024-04-03 22:29:41'),
	(57,'$','false,false,true,true,false,false,false,true,true,true,true,true,true,false,true,true,false,true,true,false,true,true,false,false,false,true,true,true,false,false,false,false,true,true,true,false,false,false,true,true,false,true,true,false,true,true,false,true,true,true,true,true,true,false,false,false,true,true,false,false','36','10','6',NULL,'2024-04-03 22:33:11','2024-04-03 22:35:14'),
	(58,'&','false,true,true,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false,false,true,true,false,false,false,true,true,true,false,false,false,true,true,false,true,false,false,true,false,false,true,false,true,true,false,false,false,true,false,true,true,false,true,false,true,false,true,true,true,false,false','38','10','6',NULL,'2024-04-03 22:39:28','2024-04-12 22:58:00'),
	(59,'*','false,false,false,false,false,false,false,false,true,false,false,false,true,false,true,false,true,false,false,true,true,true,false,false,true,true,true,true,true,false,false,true,true,true,false,false,true,false,true,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','42','10','6',NULL,'2024-04-03 22:57:28','2024-04-03 22:57:28'),
	(60,'^','false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','94','10','6',NULL,'2024-04-03 22:58:23','2024-04-03 22:58:26'),
	(61,'`','false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','96','10','6',NULL,'2024-04-03 22:58:43','2024-04-03 22:58:43'),
	(62,'\"','false,false,false,false,false,false,false,true,false,true,false,false,false,true,false,true,false,false,false,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','34','10','6',NULL,'2024-04-03 23:03:26','2024-04-03 23:03:26'),
	(63,':','false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false','58','10','6',NULL,'2024-04-03 23:03:41','2024-04-03 23:03:41'),
	(64,';','false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,false,false,false','59','10','6',NULL,'2024-04-03 23:04:00','2024-04-12 22:53:59'),
	(65,'\'','false,false,false,false,false,false,false,false,false,true,true,false,false,false,true,true,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','39','10','6',NULL,'2024-04-03 23:05:02','2024-04-03 23:05:05'),
	(66,'░','false,true,false,false,true,false,false,false,true,false,false,true,true,false,false,true,false,false,false,true,false,false,true,false,false,false,true,false,false,true,true,false,false,true,false,false,false,true,false,false,true,false,false,false,true,false,false,true,true,false,false,true,false,false,false,true,false,false,true,false','49','10','6',NULL,'2024-04-03 23:06:13','2024-04-03 23:06:13'),
	(67,'▒','false,true,false,true,false,true,true,false,true,false,true,false,false,true,false,true,false,true,true,false,true,false,true,false,false,true,false,true,false,true,true,false,true,false,true,false,false,true,false,true,false,true,true,false,true,false,true,false,false,true,false,true,false,true,true,false,true,false,true,false','49','10','6',NULL,'2024-04-03 23:07:39','2024-04-03 23:07:39'),
	(68,'▓','false,true,true,false,true,true,true,true,false,true,true,false,true,false,true,true,false,true,false,true,true,false,true,true,true,true,false,true,true,false,true,false,true,true,false,true,false,true,true,false,true,true,true,true,false,true,true,false,true,false,true,true,false,true,false,true,true,false,true,true','49','10','6',NULL,'2024-04-03 23:10:39','2024-04-03 23:10:39'),
	(69,'█','true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true','9619','10','6',NULL,'2024-04-03 23:10:56','2024-04-03 23:10:56'),
	(70,'▄','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true','50','10','6',NULL,'2024-04-03 23:11:39','2024-04-03 23:11:39'),
	(71,'▌','true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false','9604','10','6',NULL,'2024-04-03 23:11:52','2024-04-03 23:11:52'),
	(72,'▐','false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true,false,false,false,true,true,true','9612','10','6',NULL,'2024-04-03 23:12:03','2024-04-03 23:12:03'),
	(73,'▀','true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','50','10','6',NULL,'2024-04-03 23:12:24','2024-04-03 23:12:24'),
	(74,'■','false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,false,false,true,true,true,true,false,false,true,true,true,true,false,false,true,true,true,true,false,false,true,true,true,true,false,false,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false','39','10','6',NULL,'2024-04-03 23:13:20','2024-04-03 23:13:20'),
	(75,' ','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','9632','10','6',NULL,'2024-04-03 23:13:36','2024-04-03 23:13:36'),
	(76,'∙','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,false,false,true,true,true,true,false,false,true,true,true,true,false,false,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','183','10','6',NULL,'2024-04-03 23:14:36','2024-04-03 23:15:44'),
	(77,'·','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,true,true,true,true,false,false,true,true,true,true,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','8729','10','6',NULL,'2024-04-03 23:16:05','2024-04-03 23:16:05'),
	(78,'÷','false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,true,true,true,true,true,true,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false','43','10','6',NULL,'2024-04-03 23:16:36','2024-04-12 22:52:53'),
	(79,'¿','false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,true,true,false,true,false,false,false,true,true,true,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,false,false','63','10','6',NULL,'2024-04-03 23:18:27','2024-04-03 23:18:27'),
	(80,'°','false,false,false,false,false,false,false,false,true,true,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false','176','10','6',NULL,'2024-04-03 23:20:42','2024-04-03 23:20:42'),
	(81,'a','false,false,false,false,false,false,false,true,true,true,true,false,false,false,false,false,true,true,false,false,false,false,false,true,false,true,true,true,true,true,true,true,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false','97','10','6',NULL,'2024-04-03 23:53:38','2024-04-12 00:42:35'),
	(82,'b','true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,true,true,true,false,true,false,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,true,true,true,true,true,true,false','98','10','6',NULL,'2024-04-04 00:39:19','2024-04-12 00:48:44'),
	(83,'c','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,true,true,false,true,true,true,true,false','99','10','6',NULL,'2024-04-12 00:43:46','2024-04-12 00:43:46'),
	(84,'d','false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,true,true,true,true,true,true,true,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,false,true,false,true,true,true,true,true','100','10','6',NULL,'2024-04-12 00:44:03','2024-04-12 00:44:03'),
	(85,'e','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,true,true,true,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,true,false,false,true,true,false,true,true,true,true,false','101','10','6',NULL,'2024-04-12 00:44:15','2024-04-12 00:44:16'),
	(86,'f','false,false,false,true,true,true,false,false,true,true,false,false,false,false,true,false,false,false,true,true,true,true,true,true,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false','102','10','6',NULL,'2024-04-12 00:46:06','2024-04-12 00:57:44'),
	(87,'g','false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,true,false,false,true,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,true,false,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false','103','10','6',NULL,'2024-04-12 00:47:26','2024-04-12 00:47:57'),
	(88,'h','true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,true,true,true,false,true,true,true,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true','104','10','6',NULL,'2024-04-12 00:49:51','2024-04-12 22:38:05'),
	(89,'i','false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false','105','10','6',NULL,'2024-04-12 00:50:09','2024-04-12 00:50:22'),
	(90,'j','false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,true,false,false,false,true,true,false,false,false,false','106','10','6',NULL,'2024-04-12 00:50:51','2024-04-12 00:50:51'),
	(91,'l','false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,true,true,true,true,false','108','10','6',NULL,'2024-04-12 00:51:54','2024-04-12 00:51:54'),
	(92,'m','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,true,false,false,true,true,true,false,true,true,false,true,true,false,true,true,false,true,true,false,false,false,false,true,true,false,false,false,false,true','109','10','6',NULL,'2024-04-12 00:52:27','2024-04-12 00:52:27'),
	(93,'n','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true','110','10','6',NULL,'2024-04-12 00:52:42','2024-04-12 00:52:42'),
	(94,'o','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,true,false,false,true,false,true,false,false,false,false,true,true,false,false,false,false,true,false,true,false,false,true,false,false,false,true,true,false,false','111','10','6',NULL,'2024-04-12 00:53:11','2024-04-12 00:53:11'),
	(95,'p','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,false,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,false','112','10','6',NULL,'2024-04-12 00:54:00','2024-04-12 00:56:06'),
	(96,'q','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,true,false,false,false,true,true,false,false,false,false,true,true,true,false,false,false,true,false,true,true,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true','113','10','6',NULL,'2024-04-12 00:57:15','2024-04-12 00:57:15'),
	(97,'r','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,true,true,false,true,true,false,false,true,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false','114','10','6',NULL,'2024-04-12 00:58:11','2024-04-12 00:58:11'),
	(98,'s','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,true,false,false,false,false,false,true,true,true,true,false,false,false,false,false,true,true,true,true,false,false,true,true,false,true,true,true,true,false','115','10','6',NULL,'2024-04-12 00:59:11','2024-04-12 00:59:11'),
	(99,'t','false,false,true,true,false,false,false,false,true,true,false,false,true,true,true,true,true,true,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false','116','10','6',NULL,'2024-04-12 00:59:38','2024-04-12 00:59:38'),
	(100,'u','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false','117','10','6',NULL,'2024-04-12 01:00:15','2024-04-12 01:00:15'),
	(101,'v','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,true,true,true,false,false,false,true,true,false,false,false,false,true,true,false,false','118','10','6',NULL,'2024-04-12 01:00:31','2024-04-12 01:00:31'),
	(102,'w','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,true,false,true,true,false,true,true,false,true,true,false,true,true,true,true,true,true,true,false,true,false,false,true,false','119','10','6',NULL,'2024-04-12 01:00:52','2024-04-12 01:01:24'),
	(103,'x','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,true,true,false,true,false,false,true,false,false,true,true,true,false,false,false,false,true,true,true,false,false,true,false,false,true,false,true,true,false,false,true,true','120','10','6',NULL,'2024-04-12 01:02:25','2024-04-12 01:02:25'),
	(104,'z','false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,false,false,false,false,true,true,true,true,true,true','122','10','6',NULL,'2024-04-12 01:03:26','2024-04-12 01:03:26'),
	(105,'{','false,false,false,true,true,true,false,false,true,true,false,false,false,false,true,false,false,false,false,false,true,true,false,false,true,true,true,false,false,false,true,true,true,false,false,false,false,false,true,true,false,false,false,false,true,false,false,false,false,false,true,true,false,false,false,false,false,false,true,true','123','10','6',NULL,'2024-04-12 22:49:40','2024-04-12 22:50:26'),
	(106,'k','true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,true,true,false,false,true,true,false,true,false,true,true,false,false,true,true,true,false,false,false,true,false,true,true,false,false,true,false,false,true,true,false,true,false,false,false,true,true','107','10','6',NULL,'2024-04-12 23:05:09','2024-04-12 23:05:09'),
	(107,'0','false,false,true,true,false,false,false,true,true,true,true,false,false,true,false,false,true,false,true,true,false,false,true,true,true,false,false,false,false,true,true,false,false,false,false,true,true,true,false,false,true,true,false,true,false,false,true,false,false,true,true,true,true,false,false,false,true,true,false,false','48','10','6',NULL,'2024-06-06 11:20:21','2024-06-06 11:20:21');

/*!40000 ALTER TABLE `tbl_fonts` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
